apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: qpa
  name: imageconverter
  labels:
    component: imageconverter
spec:
  replicas: 3
  selector:
    matchLabels:
      component: imageconverter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        component: imageconverter
      annotations:
        prometheus.custom/enable_scrape: "true"
        prometheus.custom/scrape_port: "4300"
        prometheus.custom/metrics_path: "/actuator/prometheus"
    spec:
      containers:
        - name: imageconverter
          imagePullPolicy: Always
          image: gjani/laboschqpa-imageconverter:master
          command: ["java", "-jar", "-Dspring.profiles.active=gke_prod", "laboschqpa.imageconverter.jar"]
          readinessProbe:
            httpGet:
              path: /health/ping
              port: 4300
            initialDelaySeconds: 8
            periodSeconds: 4
          ports:
            - containerPort: 4300
          volumeMounts:
            - mountPath: "/app/secret/"
              name: secrets
              readOnly: true
      volumes:
        - name: secrets
          secret:
            secretName: laboschqpa-imageconverter-secrets
